pipeline {
    agent any

    environment {
        // Bind AWS credentials stored in Jenkins under 'AWS-ACCESS-KEYS' to environment variables
        AWS_ACCESS_KEY_ID     = credentials('AWS-ACCESS-KEYS').accessKey
        AWS_SECRET_ACCESS_KEY = credentials('AWS-ACCESS-KEYS').secretKey
    }

    stages {
        stage('Terraform Init') {
            steps {
                script {
                    echo 'Initializing Terraform...'
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    echo 'Planning Terraform changes...'
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    echo 'Applying Terraform changes...'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Terraform Destroy') {
            steps {
                script {
                    input message: 'Do you want to destroy the resources?', ok: 'Yes'
                    echo 'Destroying Terraform resources...'
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
    }
}